services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: homeassistant
    network_mode: host
    environment:
      - PUID=3000
      - PGID=3000
      - TZ=New_York/America
    volumes:
    - type: bind
      source: /var/lib/docker/volumes/docker-nfs/homeassistant/
      target: /config
    restart: unless-stopped
