services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    ports:
      - 15168:15168
      - 15169:15169
    restart: unless-stopped
    volumes:
      - type: bind
        source: /var/lib/docker/volumes/cloud-nfs/data
        target: /data
      - nextcloud-config:/config
    
    networks:
      - media

networks:
  media:
    external: true

volumes:
  nextcloud-config:
    external: true