services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=New_York/America
    volumes:
      - lidarr-local-config:/config
      - type: bind
        source: /var/lib/docker/volumes/contents-nfs/
        target: /content
    ports:
      - 8686:8686
    restart: unless-stopped

    networks:
      - media

networks:
  media:
    external: true

volumes:
  lidarr-local-config:
    external: true