services:
  npm:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    container_name: npm
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /data/compose/7/data:/data
      - /data/compose/7/letsencrypt:/etc/letsencrypt

    networks:
      - media

networks:
  media:
    external: true